name: blog-post-create-issues
on:
  push:
    branches: [ master ]
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: collect-titles
      run: "grep -E '@name\\s*\\=' ./src/blog/ -R > posts.txt && cat posts.txt"
    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require("fs")
          const result = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          const issues = Object.fromEntries(result.data.map(x => [x.title, x]))
          let lines = fs.readFileSync('posts.txt').toString().split('\n')
          lines.forEach(l => {
          	  f = f.trim()
          	  if (!f) return
              let [f, nameLine] = l.split(':')
              const labels = ["blog-post"]
              const body = fs.readFileSync(f).toString().split('\n').map(x => {
                x = x.trim()
                if (x.match(/^@labels/)) labels = labels.concat(x.slice(x.indexOf('=')+1).trim()
                return x
              }).filter(x => !x.match(/^@/))
              	.join('\n')
              	.replace(/(\[[^\]]*\]\()(\/[^\)]+\))/, "$1https://github.com/ktravis/kylemtravis/blob/master$2")
              	.replace(/(src=")(\/[^"]+")/, "$1https://github.com/ktravis/kylemtravis/blob/master$2")
              const title = nameLine.slice(nameLine.indexOf('=')+1).trim()
              if (title in issues) {
                  const found = issues[title]
                  github.issues.update({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: found.number,
                      labels: found.labels.concat(labels),
                      title,
                      body,
                  })
                  return
              }
              github.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title,
                  body,
                  labels,
              })
          })
